name: Deploy Docs

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "docs/**"
  pull_request:
    branches: main
    paths:
      - "docs/**"

jobs:
  deploy-docs:
    name: Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./docs

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "deno install"

      - name: Build step
        run: "deno run build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "google-videodiscovery"
          entrypoint: "server/entry.mjs"
          root: "dist"
